Paypal Express gateway: Fix missing address
Calling PaypalExpressResponse#address when the response didn't contain
any address information was causing a dereference error:

  NoMethodError: undefined method `[]' for nil:NilClass

Closes #628.